# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmpp_http_upload', '0003_auto_20161026_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
